apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: checkoutservice
spec:
  hosts:
  - checkoutservice.default.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 5050
    protocol: grpc
  resolution: STATIC
  addresses:
  - 240.255.3.4
  endpoints:
  - address: 135.90.77.34
    ports:
      grpc: 15443
---
