apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: currencyservice
spec:
  hosts:
  - currencyservice.default.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 7000
    protocol: grpc
  resolution: STATIC
  addresses:
  - 240.255.3.5
  endpoints:
  - address: 135.90.77.34
    ports:
      grpc: 15443
---
