apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productcatalogservice
spec:
  hosts:
  - productcatalogservice.default.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 3550
    protocol: grpc
  resolution: STATIC
  addresses:
  - 240.255.1.2
  endpoints:
  - address: 159.122.148.147
    ports:
      grpc: 15443
---
