apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: adservice
spec:
  hosts:
  - adservice.default.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 9555
    protocol: grpc
  resolution: STATIC
  addresses:
  - 240.255.3.2
  endpoints:
  - address: GATEWAY3
    ports:
      grpc: 15443
---
